### ISSUE TITLE
Use ACE_UNIMPLEMENTED_FUNC instead of ACE_Copy_Disabled

### ISSUE THREAD

**Issue by jwillemsen** [LASAGNE-Open-Systems/LASAGNE-Core#37]
It is better to use ACE_UNIMPLEMENTED_FUNC instead of ACE_Copy_Disabled because it reduces footprint and with C++11 enabled ACE_UNIMPLEMENTED_FUNC will result in deleted functions which give a clear compiler error when someone tries to use them

**Comment by mathersm-dst** [comment]
Addressed by pull request #50.
