### ISSUE TITLE
Add appveyor/travis-ci integration

### ISSUE THREAD

**Issue by jwillemsen** [LASAGNE-Open-Systems/LASAGNE-Core#38]
For testing pull requests a appveyor and travis-ci integration setup will greatly simplify work, see ACE/TAO and OpenDDS for examples

**Comment by mathersm-dst** [comment]
AppVeyor seems to be a bit of a pain to configure for a repo belonging to an organisation on GitHub. I can configure an account for my repos no worries but I seem to be missing something to get it to refer to the LASAGNE-Open-Systems/LASAGNE-Core repo directly. Did you have to do anything special for the DOCGroup repos?

**Comment by jwillemsen** [comment]
See https://www.appveyor.com/docs/team-setup, at the bottom there is a description how to setup this

**Comment by mathersm-dst** [comment]
Initial integration is in place. See #49
