### ISSUE TITLE
Missing /lib directory?

### ISSUE THREAD

**Issue by bluetyson** [LASAGNE-Open-Systems/LASAGNE-Core#40]
As mentioned here 

LASAGNE-Core/docs/html/documentation/linux_notes.html

export PATH = $PATH;[extracted path]/LASAGNE-Core/bin;[extracted path]/LASAGNE-Core/lib
export LD_LIBRARY_PATH = $LD_LIBRARY_PATH;[extracted path]/LASAGNE-Core/lib

**Comment by DDominish** [comment]
The .../lib directory will be created when you have a successful build.
1) On Linux you only need to add the lib directories to the LD_LIBRARY_PATH.  The bin directories are added to the PATH. 
2) On Windows you need to add both the bin and lib directories to the PATH

**Comment by bluetyson** [comment]
Right, thanks

**Comment by mathersm-dst** [comment]
We could just add an empty lib directory to avoid this kind of confusion for people.

@bluetyson as it stands you'll need to set the environment variables before you generate project/workspace/make files using MPC. Then you when you enact the build you'll see the 'lib' directory created and populated.

**Comment by mathersm-dst** [comment]
Fixed by #44
