### ISSUE TITLE
Update contribution guidelines to reflect develop as the target for pull requests

### ISSUE THREAD

**Issue by mathersm-dst** [LASAGNE-Open-Systems/LASAGNE-Core#43]
We've received a couple of pull requests recently that have directly targeted master. While this might be common practice for other repos it doesn't fit with our workflow.

We need to update the contributing section of the readme markdown to make this clear and easy for everyone.

**Comment by jwillemsen** [comment]
Would help to set the default branch to develop on github, see settings/branches

**Comment by mathersm-dst** [comment]
Updated the contributing section in #46 and set the default branch on GitHub to develop as well.
