### ISSUE TITLE
No changelog to advise of changes between versions

### ISSUE THREAD

**Issue by mathersm-dst** [LASAGNE-Open-Systems/LASAGNE-Core#77]
Some projects use either the readme markdown or a separate file to record changes between versions.
This should become part of the release process.

**Comment by jwillemsen** [comment]
In ACE/TAO we are using a news file with the major changes (which we also add to the github release information) and we generate a changelog with all git log entries made in that release which is useful for users to search quickly especially when they are not connected to the internet

**Comment by mathersm-dst** [comment]
Added in pull request #79
